### ISSUE TITLE
Alternative to the standard email notification text

### ISSUE THREAD

**Issue by iherman** [w3c/calendar#104] opened 2023-05-23 15:11 UTC
Here is a frequent scenario I do

1. Have a WG call, whose calendar entry is part of a regular series
2. After the call, I open up the call's calendar entry, choose the minutes' tab, add the link to the minutes
3. I push the "Update but don't send notifications" button
4. Use my own mail client to email the WG in which I announce the link to the minutes

The reason I use 3-4, instead of relying on the calendar system's notification mechanism is because the notification text going out is the generic one and cannot be adapted to the situation (namely that the minutes' link has been added). If there was, for example, a simple templating mechanism for a situation like this, or simply a box where I could type in my own alternative to the standard text, 3-4 could be changed for a single notification step...

**Comment by plehegar** [comment] 2023-11-07 16:21
Duplicate of #102

**Closed as completed by plehegar** 2023-11-07 16:21 UTC
Labels: enhancement
