### ISSUE TITLE
Duplicates event notification

### ISSUE THREAD

**Issue by plehegar** [w3c/calendar#52] opened 2021-07-13 20:21 UTC
Sending a new calendar event results in about 3-4 emails being sent to the WG list, including duplicates of the calendar event. 

via @wareid

This might be a duplicate from #22 , which is supposed to be fixed by now.

@wareid , can you confirm that the bug is still happening? We added a "Update but don't send notifications" button 10 days ago to give more control about notifications.

**Comment by vivienlacourba** [comment] 2021-07-15 08:43
This might actually be a duplicate of https://github.com/w3c/calendar/issues/45 which shoudl now be fixed (@jean-gui will check if that issue has come back).

**Comment by vivienlacourba** [comment] 2021-07-15 09:03
@wareid I'm closing this issue please reply to it if you notice any new duplicate calendar emails sent on your lists and I'll reopen this issue.

**Closed by vivienlacourba** 2021-07-15 09:03 UTC
Labels: duplicate, question
